### ISSUE TITLE
react 头像集合 component

### ISSUE THREAD

**Issue by billie66** [happypeter/react-meteor-book#19]
```
data = {
  name: "jon",
  name: "peter"
}
```

一个 div 里面包含可以显示四个头像的位置，默认这四个位置都是灰色圆形，每次我填写一个 data 项目，就可以填充一个头像进去。

头像是已经托管在公网上的，例如 http://media.haoduoshipin.com/peter.jpg

**Comment by billie66** [comment]
目录结构：

![screen shot 2015-08-29 at 6 00 49 pm](https://cloud.githubusercontent.com/assets/102444/9561435/f5f096e4-4e77-11e5-9b54-4ffef8eded6f.png)

app/App.js 文件内容，如下：

``` js
var _ = require('underscore');
var React = require('react');
var Box = require('./Box.js')


var App = React.createClass({
  getInitialState: function() {
    return {
      groups: {
        one: ['peter','','',''],
        two: ['','','peter',''],
        three: ['','peter','',''],
        four: ['peter','','',''],
        five: ['','','','peter']
      }
    };
  },

  render: function() {
    var boxes = _.map(this.state.groups, function(g, key){
      return <Box group={g} key={key} />
    });

    return (
      <div className="boxes-area clearfix">
        {boxes}
      </div>
    );
  }
});

React.render(<App />, document.getElementById('app'));
```

app/Box.js 文件内容如下：

``` js
require("./main.css");
var _ = require('underscore');
var React = require('react');

var Box = React.createClass({
  getInitialState: function() {
    return {
      names: this.props.group
    };
  },

  render: function() {
    var names = _.map(this.state.names, function(name, index) {
      if (name !== '') {
        var image = 'http://media.haoduoshipin.com/modern/avatar/' + name + '.jpg';
        return (
            <li className="avatar" key={index}>
              <img src={image} />
            </li>
          );
      } else {
        return (<li className="avatar" key={index}></li>);
      }
    });

    return (
      <div className="box-wrapper">
        <ul className="box clearfix">
          {names}
        </ul>
      </div>
    );
  }
});

module.exports = Box;
```

app/main.css 文件内容如下：

``` css
* {
  box-sizing: border-box;
}

body {
  margin: 0;
  padding: 0;
  background-color: deeppink;
}

ul {
  margin: 0;
  padding: 0;
  list-style-type: none;
}

.clearfix:before, .clearfix:after {
  content: '';
  display: table;
}

.clearfix:after {
  clear: both;
}

#app {
  width: 100%;
  margin: 50px auto;
  background-color: deeppink;
}

.box-wrapper {
  width: 100%;
  background-color: deeppink;
  margin: 0 auto;
  border: 1px solid yellow;
}
.box {
  width: 386px;
  margin: 1em auto;
  border: 1px solid yellow;
  background-color: #fff;
}

.avatar {
  width: 5em;
  height: 5em;
  border-radius: 50%;
  background-color: #eee;
  float: left;
  margin: .5em;
}

.avatar img {
  display: block;
  width: 5em;
  height: 5em;
  border-radius: 50%;
}

@media (min-width: 800px) {
  .box-wrapper {
    width: 50%;
    float: left;
  }
}
```

public/index.html 文件内容如下：

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>React Book Demo</title>
</head>
<body>
  <div id="app"></div>
  <script src="bundle.js"></script>
</body>
</html>
```

webpack.config.js 文件内容如下：

``` js
module.exports = {
  entry: "./app/App.js",
  output: {
    filename: "public/bundle.js"
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel'
      },
      {
        test: /\.css?$/,
        loader: 'style!css'
      }
    ]
  }
};
```

package.json 文件内容如下：

``` json
{
  "name": "react-book-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^0.13.3"
  },
  "devDependencies": {
    "babel-core": "^5.8.23",
    "babel-loader": "^5.3.2",
    "css-loader": "^0.16.0",
    "node-libs-browser": "^0.5.2",
    "style-loader": "^0.12.3",
    "underscore": "^1.8.3",
    "webpack": "^1.12.0"
  }
}
```
